# Dept for Culture, Media & Sport 

## Participation Survey 2023â€“24 annual publication

In [7]:
import pandas as pd
import os
from pathlib import Path

In [8]:
DATA_DIR = Path('../data/Revised_DCMS_Participation_Survey_annual_23-24_data_tables__Oct_2024_.ods')
OUT_DIR = Path('../src/data/dcms/_data')

sheet_description_dict = {
    'Table_A3': 'Adults who engaged with arts in person',
    'Table_A5': 'Art exhibition',
    'Table_A7': 'Theatre, musical, ballet or opera',
    'Table_A9': 'Literature and poetry events',
    'Table_A11': 'A cinema screening',
    'Table_A13': 'A craft exhibition',
    'Table_A15': 'A live music event',
    'Table_A17': 'An arts festival',
    'Table_A19': 'A street art event',
    'Table_A21': 'A live dance event',
    'Table_A23': 'A fashion show',
    'Table_A25': 'A comedy event',
    'Table_A27': 'An in-persion e-sports event',
    'Table_A29': 'Some other cultural event',
    'Table_A31': 'Not attended any events',
    'Table_A33': 'Written stories, plays, or poetry',
    'Table_A35': 'Read books or graphic novels',
    'Table_A37': 'Written or performed music',
    'Table_A39': 'Painting, drawing',
    'Table_A41': 'Crafts',
    'Table_A43': 'Performed a drama / dance routine',
    'Table_A45': 'Designed or programmed video games',
    'Table_A47': 'Made films or videos',
    'Table_A49': 'Photography',
    'Table_A51': 'Read news in a printed newspaper',
    'Table_A53': 'Other arts or creative activities',
    'Table_A55': 'Not participated'
}

columns_of_interest = [
    'Response Breakdown ',
    'Percentage of respondents 2023/24',
    'Percentage of respondents 2023/24 Lower estimate',
    'Percentage of respondents 2023/24 Upper estimate',
    '2023/24 No. of respondents',
    '2023/24 Base',
    'LAD23 code'
]

engagement = [
    'Table_A3',
    'Table_A5',
    'Table_A7'
]

attendance = [
    'Table_A9',
    'Table_A11',
    'Table_A13',
    'Table_A15',
    'Table_A17',
    'Table_A19',
    'Table_A21',
    'Table_A23',
    'Table_A25',
    'Table_A27',
    'Table_A29',
    'Table_A31'
]

participation = [
    'Table_A33',
    'Table_A35',
    'Table_A37',
    'Table_A39',
    'Table_A41',
    'Table_A43',
    'Table_A45',
    'Table_A47',
    'Table_A48',
    'Table_A49',
    'Table_A51'
]

### Read the raw data

In [9]:
data = pd.read_excel(DATA_DIR, engine='odf', sheet_name=None, skiprows=4)

{'Cover_sheet':    More information about Participation Survey is available at:  Unnamed: 1  \
 0         The Participation Survey statistics website                   NaN
 1                            Responsible statistician                   NaN
 2                      Donilia Asgill and Ella Bentin                   NaN
 3                             Statistical enquiries:                    NaN
 4                                evidence@dcms.gov.uk                   NaN
 5   Notes:All notes can be found in the Notes shee...                   NaN
 6   In 2023/24, DCMS partnered with Arts Council E...                   NaN
 7   Due to the ACE-boosted sample in the 23/24 sur...                   NaN
 8   The Participation Survey is only asked of adul...                   NaN
 9                           Scottish Household Survey                   NaN
 10                          National Survey for Wales                   NaN
 11      Northern Ireland Continuous Household Survey.                   NaN

     Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  \
 0          NaN         NaN         NaN         NaN         NaN         NaN
 1          NaN         NaN         NaN         NaN         NaN         NaN
 2          NaN         NaN         NaN         NaN         NaN         NaN
 3          NaN         NaN         NaN         NaN         NaN         NaN
 4          NaN         NaN         NaN         NaN         NaN         NaN
 5          NaN         NaN         NaN         NaN         NaN         NaN
 6          NaN         NaN         NaN         NaN         NaN         NaN
 7          NaN         NaN         NaN         NaN         NaN         NaN
 8          NaN         NaN         NaN         NaN         NaN         NaN
 9          NaN         NaN         NaN         NaN         NaN         NaN
 10         NaN         NaN         NaN         NaN         NaN         NaN
 11         NaN         NaN         NaN         NaN         NaN         NaN

     Unnamed: 8  Unnamed: 9  ...  Unnamed: 52  Unnamed: 53  Unnamed: 54  \
 0          NaN         NaN  ...          NaN          NaN          NaN
 1          NaN         NaN  ...          NaN          NaN          NaN
 2          NaN         NaN  ...          NaN          NaN          NaN
 3          NaN         NaN  ...          NaN          NaN          NaN
 4          NaN         NaN  ...          NaN          NaN          NaN
 5          NaN         NaN  ...          NaN          NaN          NaN
 6          NaN         NaN  ...          NaN          NaN          NaN
 7          NaN         NaN  ...          NaN          NaN          NaN
 8          NaN         NaN  ...          NaN          NaN          NaN
 9          NaN         NaN  ...          NaN          NaN          NaN
 10         NaN         NaN  ...          NaN          NaN          NaN
 11         NaN         NaN  ...          NaN          NaN          NaN

     Unnamed: 55  Unnamed: 56  Unnamed: 57  Unnamed: 58  Unnamed: 59  \
 0           NaN          NaN          NaN          NaN          NaN
 1           NaN          NaN          NaN          NaN          NaN
 2           NaN          NaN          NaN          NaN          NaN
 3           NaN          NaN          NaN          NaN          NaN
 4           NaN          NaN          NaN          NaN          NaN
 5           NaN          NaN          NaN          NaN          NaN
 6           NaN          NaN          NaN          NaN          NaN
 7           NaN          NaN          NaN          NaN          NaN
 8           NaN          NaN          NaN          NaN          NaN
 9           NaN          NaN          NaN          NaN          NaN
 10          NaN          NaN          NaN          NaN          NaN
 11          NaN          NaN          NaN          NaN          NaN

     Unnamed: 60                                        Unnamed: 61
 0           NaN                                                NaN
 1           NaN                                                NaN
 2           NaN  25th July 2024 - We have revised the figure in...
 3           NaN                                                NaN
 4           NaN                                                NaN
 5           NaN                                                NaN
 6           NaN                                                NaN
 7           NaN                                                NaN
 8           NaN                                                NaN
 9           NaN                                                NaN
 10          NaN                                                NaN
 11          NaN                                                NaN

 [12 rows x 62 columns],
 'Table_of_contents':          Notes      Notes related to the data in this spreadsheet   Notes.1
 0     Table A1  Adult engagement with the arts in the last 12 ...  Table 1a
 1     Table A2  Demographics - physical engagement in the last...  Table 1b
 2     Table A3  Local authorities - physical engagement in the...       NaN
 3     Table A4  Demographics - physical attendance in the last...       NaN
 4     Table A5  Local authorities - physical engagement in the...       NaN
 ..         ...                                                ...       ...
 137  Table J11     Adult digital skills, April 2022 to March 2024  Table 8i
 138  Table J12  Demographics - adults who did digital or onlin...  Table 8h
 139  Table J13            Data security, April 2022 to March 2024  Table 8j
 140  Table J14  Digital methods of identification, April 2022 ...  Table 8k
 141  Table J15                Use of data, May 2023 to March 2024  Table 8l

 [142 rows x 3 columns],
 'Notes':      Note 3  \
 0    Note 4
 1    Note 5
 2    Note 6
 3    Note 7
 4    Note 8
 5    Note 9
 6   Note 10
 7   Note 11
 8   Note 12
 9   Note 13
 10  Note 14
 11  Note 15
 12  Note 16
 13  Note 17
 14  Note 18
 15  Note 19
 16  Note 20
 17  Note 21
 18  Note 22
 19  Note 23
 20  Note 24
 21  Note 25
 22  Note 26
 23  Note 27

    Due to the way this question is asked, this cell has been rephrased to be a more precise description. The results are comparable with the 2022/23 results.
 0   These response options were not in the 2022/23...
 1   These questions were not in the 2022/23 survey...
 2   These questions were not in the 2023/24 paper ...
 3   These options for barriers to engaging with th...
 4   In the 2022/23 questionnaire, a custom questio...
 5   Cells marked with 'x' indicate data suppressio...
 6   Due to the sample boost by ACE this year, loca...
 7   These options for barriers to engaging with th...
 8   These options for barriers to engaging with li...
 9   These options for barriers to engaging with li...
 10  These questions were not in the 2023/24 paper ...
 11  These options for barriers to engaging with he...
 12  Due to a scripting error in Q1 and Q2, the phy...
 13  These options for barriers to engaging with he...
 14  These options for barriers to engaging with mu...
 15  This was asked of all respondents online, but ...
 16  These options for barriers to engaging with mu...
 17  All questions in this table are additions due ...
 18  Arts Council England is the national developme...
 19  This option was "football" in the 22/23 survey...
 20  The Coventry City of Culture 2021 events took ...
 21  The comparison is made against the 22/23 figur...
 22  Household Acorn Â© CACI Limited 2013 - 2022 Sou...
 23  03 October 2024 - Some figures in tables F3 an...                                                                                                          ,
 'Table_A1':                                              Question  \
 0   Engaged with the arts physically (attended an ...
 1   The most frequent level at which adults attend...
 2   The most frequent level at which adults attend...
 3   The most frequent level at which adults attend...
 4   The most frequent level at which adults attend...
 ..                                                ...
 82  Barriers to engaging with the arts in the last...
 83  Barriers to engaging with the arts in the last...
 84  Barriers to engaging with the arts in the last...
 85  Engaged with the arts physically and digitally...
 86  Engaged with the arts physically or digitally ...

                                   Response Breakdown   \
 0   Any event in rows 18 to 30 or activity in rows...
 1                                At least once a week
 2   Less often than once a week but at least once ...
 3   Less often than once a month but at least 3 or...
 4                         Twice in the last 12 months
 ..                                                ...
 82           Due to COVID-19 restrictions or concerns
 83                                  Some other reason
 84                            No reason in particular
 85                                              Total
 86                                              Total

    Change between 2022/23 and 2023/24 Percentage of respondents 2023/24  \
 0                            Increase                         90.416034
 1                            Decrease                         59.379772
 2                            Increase                          15.40767
 3                            Increase                         14.248573
 4                            Increase                          6.064548
 ..                                ...                               ...
 82                           Decrease                          2.670108
 83                           Decrease                          0.457969
 84                          No Change                         27.581066
 85                           Increase                         35.470541
 86                           Increase                         91.373222

    Percentage of respondents 2023/24 Lower estimate  \
 0                                         90.227267
 1                                         59.071718
 2                                         15.189903
 3                                         14.033363
 4                                          5.918739
 ..                                              ...
 82                                         2.382761
 83                                         0.349239
 84                                        26.689838
 85                                        35.187817
 86                                        91.191951

    Percentage of respondents 2023/24 Upper estimate  \
 0                                         90.601535
 1                                         59.687091
 2                                         15.627984
 3                                         14.466528
 4                                          6.213711
 ..                                              ...
 82                                         2.991046
 83                                         0.600348
 84                                        28.490489
 85                                        35.754283
 86                                        91.551108

    2023/24 No. of respondents  2023/24 Base  \
 0                      157205        171734
 1                       98640        157201
 2                       22459        157201
 3                       20560        157201
 4                        8624        157201
 ..                        ...           ...
 82                        407         14454
 83                         67         14454
 84                       3988         14454
 85                      63202        171735
 86                     158756        171734

     Percentage of respondents 2022/23  \
 0                           89.065359
 1                           70.243209
 2                           11.905962
 3                            9.050847
 4                            4.341675
 ..                                ...
 82                          11.883852
 83                           1.435091
 84                          26.317342
 85                          27.092762
 86                          90.333443

     Percentage of respondents 2022/23 Lower estimate  \
 0                                          88.632267
 1                                          69.621305
 2                                          11.489205
 3                                           8.680362
 4                                           4.083569
 ..                                               ...
 82                                         10.661381
 83                                          1.051250
 84                                         24.524063
 85                                         26.516491
 86                                         89.919297

     Percentage of respondents 2022/23 Upper estimate  \
 0                                          89.483907
 1                                          70.857710
 2                                          12.335728
 3                                           9.435510
 4                                           4.615309
 ..                                               ...
 82                                         13.225745
 83                                          1.956314
 84                                         28.192770
 85                                         27.676841
 86                                         90.732329

     2022/23 No. of respondents  2022/23 Base
 0                      29860.0       33231.0
 1                      21324.0       29837.0
 2                       3446.0       29837.0
 3                       2582.0       29837.0
 4                       1244.0       29837.0
 ..                         ...           ...
 82                       409.0        3354.0
 83                        49.0        3354.0
 84                       840.0        3354.0
 85                      9106.0       32913.0
 86                     30205.0       33178.0

 [87 rows x 13 columns],
 'Table_A2':     Engaged with the arts physically (attended an event or participated in an activity in person) in the last 12 months  \
 0                                                  Age
 1                                                  Age
 2                                                  Age
 3                                                  Age
 4                                                  Age
 ..                                                 ...
 195                                         Loneliness
 196                                         Loneliness
 197                                         Loneliness
 198                                         Loneliness
 199                                         Loneliness

     Any event in rows 18 to 30 or activity in rows 34 to 44 of Table A1  \
 0                                             16 to 19
 1                                             20 to 24
 2                                             25 to 29
 3                                             30 to 34
 4                                             35 to 39
 ..                                                 ...
 195                                    Often or always
 196                                   Some of the time
 197                                       Occasionally
 198                                        Hardly ever
 199                                              Never

       Increase  90.416034  90.227267  90.601535  157205  171734  89.065359  \
 0    No Change  89.680488  88.778184  90.517989    6198    6875  90.958721
 1     Decrease  88.886897  87.980662  89.732777    7195    7991   92.62992
 2    No Change  90.807535  90.129583  91.443342   10118   11062  91.744559
 3    No Change  90.231952  89.615242  90.815791   12138   13365  90.452295
 4    No Change  90.760940  90.159849  91.328845   12298   13445  89.407142
 ..         ...        ...        ...        ...     ...     ...        ...
 195  No Change  86.412878  85.625931  87.163200    9624   11047  84.923618
 196   Increase  91.557045  91.155751  91.941741   27084   29340  89.773683
 197   Increase  91.958837  91.628940  92.276829   39201   42323  90.900369
 198  No Change  93.237325  92.945097  93.518292   45643   48479  92.335202
 199   Increase  89.035579  88.594314  89.461803   31907   35160  87.344194

      88.632267  89.483907 29860   33231
 0    88.839722  92.708409  1137  1247.0
 1    90.876481  94.068363  1489  1593.0
 2    90.220747  93.049222  2035  2201.0
 3    88.998114  91.732125  2293  2504.0
 4    87.948262  90.708081  2338  2585.0
 ..         ...        ...   ...     ...
 195  83.105738  86.577481  1815  2147.0
 196  88.813011  90.660534  5142  5687.0
 197  90.136901   91.61024  7463  8156.0
 198  91.653353  92.965625  8470  9093.0
 199  86.345986  88.279332  6011  6814.0

 [200 rows x 13 columns],
 'Table_A3':                                               Question  \
 0    Engaged with the arts physically (attended an ...
 1                             Local authority district
 2                             Local authority district
 3                             Local authority district
 4                             Local authority district
 ..                                                 ...
 292                           Local authority district
 293                           Local authority district
 294                           Local authority district
 295                           Local authority district
 296                           Local authority district

                                    Response Breakdown   \
 0    Any event in rows 18 to 30 or activity in rows...
 1                                                 Adur
 2                                         Amber Valley
 3                                                 Arun
 4                                             Ashfield
 ..                                                 ...
 292                                           Worthing
 293                                           Wychavon
 294                                               Wyre
 295                                        Wyre Forest
 296                                               York

      Percentage of respondents 2023/24  \
 0                            90.416034
 1                            94.290783
 2                            91.540645
 3                            90.929811
 4                            88.482225
 ..                                 ...
 292                          94.147898
 293                          93.775787
 294                          91.310575
 295                          92.477241
 296                          93.952082

      Percentage of respondents 2023/24 Lower estimate  \
 0                                           90.227267
 1                                           90.627172
 2                                           88.146623
 3                                           87.126727
 4                                           84.870164
 ..                                                ...
 292                                         91.047424
 293                                         90.864548
 294                                         87.443655
 295                                         89.286401
 296                                         90.704414

      Percentage of respondents 2023/24 Upper estimate  \
 0                                           90.601535
 1                                           96.576473
 2                                           94.028678
 3                                           93.690730
 4                                           91.320144
 ..                                                ...
 292                                         96.219199
 293                                         95.802148

### Create headlines

In [10]:

summaries = data['Table_A1']
summaries = (
    summaries.drop(columns={
    'Percentage of respondents 2023/24 Lower estimate',
    'Percentage of respondents 2023/24 Upper estimate',
    '2023/24 No. of respondents', 
    '2023/24 Base',
    'Percentage of respondents 2022/23 Lower estimate',
    'Percentage of respondents 2022/23 Upper estimate', 
    '2022/23 No. of respondents', 
    '2022/23 Base'
    })
)


summaries['Percentage of respondents 2023/24'] = (
    pd.to_numeric(summaries['Percentage of respondents 2023/24'], errors='coerce')
    .fillna(0)
    .round(0)
    .astype(int)
)
summaries['Percentage of respondents 2022/23'] = (
    pd.to_numeric(summaries['Percentage of respondents 2022/23'], errors='coerce')
    .fillna(0)
    .round(0)
    .astype(int)
)

summaries['ID'] = [f'response_{i + 1}' for i in range(len(summaries))]

summaries = summaries.set_index('ID')

summaries.to_csv(os.path.join(OUT_DIR, 'headlines.csv'))

In [11]:
sheets = [f'Table_A{i}' for i in range(3, 56, 2)]

all_filtered_data = []

for sheet in sheets:
    data = pd.read_excel(DATA_DIR, engine='odf', sheet_name=sheet, skiprows=4)
    filtered_data = data[data['LAD23 code'] == 'E08000021']
    filtered_data = filtered_data[columns_of_interest]
    filtered_data['Sheet Name'] = sheet
    filtered_data['Description'] = sheet_description_dict.get(sheet, '')
    all_filtered_data.append(filtered_data)
    print('sheet number: ' + sheet)

final_data = pd.concat(all_filtered_data, ignore_index=True)

sheet number: Table_A3
sheet number: Table_A5
sheet number: Table_A7
sheet number: Table_A9
sheet number: Table_A11
sheet number: Table_A13
sheet number: Table_A15
sheet number: Table_A17
sheet number: Table_A19
sheet number: Table_A21
sheet number: Table_A23
sheet number: Table_A25
sheet number: Table_A27
sheet number: Table_A29
sheet number: Table_A31
sheet number: Table_A33
sheet number: Table_A35
sheet number: Table_A37
sheet number: Table_A39
sheet number: Table_A41
sheet number: Table_A43
sheet number: Table_A45
sheet number: Table_A47
sheet number: Table_A49
sheet number: Table_A51
sheet number: Table_A53
sheet number: Table_A55

In [12]:
percentage_respondents = final_data.drop(columns={
    'Response Breakdown ',
    'Percentage of respondents 2023/24 Lower estimate',
    'Percentage of respondents 2023/24 Upper estimate', 
    '2023/24 No. of respondents',
    '2023/24 Base',
    'LAD23 code'
}).set_index('Description')

percentage_respondents['Percentage of respondents 2023/24'] = percentage_respondents['Percentage of respondents 2023/24'].astype(int)

# total = percentage_respondents.drop(columns={'Sheet Name'}).to_csv(os.path.join(OUT_DIR, 'articipation_survey_23_24_newcastle.csv'))
engagement_data = percentage_respondents.loc[percentage_respondents['Sheet Name'].isin(engagement)].drop(columns={'Sheet Name'}).to_csv(os.path.join(OUT_DIR, 'engagement_participation_survey_23_24_newcastle.csv'))
attendance_data = percentage_respondents.loc[percentage_respondents['Sheet Name'].isin(attendance)].drop(columns={'Sheet Name'}).to_csv(os.path.join(OUT_DIR, 'attendance_participation_survey_23_24_newcastle.csv'))
participation_data = percentage_respondents.loc[percentage_respondents['Sheet Name'].isin(participation)].drop(columns={'Sheet Name'}).to_csv(os.path.join(OUT_DIR, 'participation_participation_survey_23_24_newcastle.csv'))

In [13]:
final_data

,Response Breakdown,Percentage of respondents 2023/24,Percentage of respondents 2023/24 Lower estimate,Percentage of respondents 2023/24 Upper estimate,2023/24 No. of respondents,2023/24 Base,LAD23 code,Sheet Name,Description
0,Newcastle upon Tyne,88.693857,85.129525,91.48926,580,643,E08000021,Table_A3,Adults who engaged with arts in person
1,Newcastle upon Tyne,26.311318,22.498326,30.516084,181,643,E08000021,Table_A5,Art exhibition
2,Newcastle upon Tyne,34.532236,30.307837,39.015811,236,643,E08000021,Table_A7,"Theatre, musical, ballet or opera"
3,Newcastle upon Tyne,9.027214,6.817167,11.862524,62,643,E08000021,Table_A9,Literature and poetry events
4,Newcastle upon Tyne,54.580619,49.83312,59.246262,351,643,E08000021,Table_A11,A cinema screening
5,Newcastle upon Tyne,8.871178,6.743894,11.586122,56,643,E08000021,Table_A13,A craft exhibition
6,Newcastle upon Tyne,36.678582,32.358037,41.224433,247,643,E08000021,Table_A15,A live music event
7,Newcastle upon Tyne,18.984179,15.833322,22.593742,125,643,E08000021,Table_A17,An arts festival
8,Newcastle upon Tyne,6.631958,4.776032,9.139858,46,643,E08000021,Table_A19,A street art event
9,Newcastle upon Tyne,5.715846,3.990679,8.123696,35,643,E08000021,Table_A21,A live dance event
10,Newcastle upon Tyne,1.611832,0.841326,3.066165,10,643,E08000021,Table_A23,A fashion show
11,Newcastle upon Tyne,12.402296,9.663837,15.781194,77,643,E08000021,Table_A25,A comedy event
12,Newcastle upon Tyne,2.527328,1.425924,4.44114,15,643,E08000021,Table_A27,An in-persion e-sports event
13,Newcastle upon Tyne,1.611316,0.780849,3.295683,11,643,E08000021,Table_A29,Some other cultural event
14,Newcastle upon Tyne,25.393063,21.462171,29.771004,160,643,E08000021,Table_A31,Not attended any events
15,Newcastle upon Tyne,7.363152,5.41203,9.943737,45,643,E08000021,Table_A33,"Written stories, plays, or poetry"
16,Newcastle upon Tyne,57.970011,53.407777,62.400021,398,643,E08000021,Table_A35,Read books or graphic novels
17,Newcastle upon Tyne,9.256691,6.982996,12.17382,61,643,E08000021,Table_A37,Written or performed music
18,Newcastle upon Tyne,18.572451,15.327581,22.323158,119,643,E08000021,Table_A39,"Painting, drawing"
19,Newcastle upon Tyne,13.893975,11.215924,17.088397,98,643,E08000021,Table_A41,Crafts
20,Newcastle upon Tyne,2.31806,1.275747,4.175944,13,643,E08000021,Table_A43,Performed a drama / dance routine
21,Newcastle upon Tyne,1.608508,0.853915,3.009682,10,643,E08000021,Table_A45,Designed or programmed video games
22,Newcastle upon Tyne,3.299227,1.97961,5.449599,18,643,E08000021,Table_A47,Made films or videos
23,Newcastle upon Tyne,14.140891,11.429638,17.369163,97,643,E08000021,Table_A49,Photography
24,Newcastle upon Tyne,33.718343,29.752024,37.927937,241,643,E08000021,Table_A51,Read news in a printed newspaper
25,Newcastle upon Tyne,0.66844,0.239647,1.850234,4,643,E08000021,Table_A53,Other arts or creative activities
26,Newcastle upon Tyne,26.3943,22.413751,30.801129,150,643,E08000021,Table_A55,Not participated